### ISSUE TITLE
patikasu

### ISSUE THREAD

**Issue by jikfrzg-agf** [jikfrzg-agf/takkun#1]
## WHAT
ログイン画面のデザイン部分（機能以外）を作成する
## TODO
- [ ] login.jspを作成
- [ ] menu.jspでログインリンクをクリックした際の遷移先をlogin.jspに変更
- [ ] 画面設計書に沿ってパーツを配置

**Comment by pheasant-parakeet** [comment]
リ`君大丈夫か！！！！！！！！！？！！！！！！！

________________________________
差出人: InoueRyohei ***@***.***>
送信日r: 2024年4月12日 11:20
宛先: jikfrzg-agf/takkun ***@***.***>
CC: w　S麻 ***@***.***>; Assign ***@***.***>
件名: Re: [jikfrzg-agf/takkun] patikasu (Issue #1)


Reopened #1<https://github.com/jikfrzg-agf/takkun/issues/1>.

―
